---
# tasks file for rpmfusion

- name: Check for existing RPM Fusion repositories
  stat:
    path: /etc/yum.repos.d/rpmfusion-free.repo
  register: r_rpmfusion_check_existing

- name: Install RPM Fusion repositories
  dnf:
    name:
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
      - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
  become: yes
  when: not r_rpmfusion_check_existing.stat.exists
